# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-14 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20181206_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintions',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='主机名')),
            ],
        ),
    ]
