# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welkin', '0002_auto_20181115_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appline',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('appname', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Mainframe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=32)),
                ('paswd', models.CharField(max_length=64)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welkin.Appline')),
            ],
        ),
    ]
