# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welkin', '0003_appline_mainframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='appline',
            name='line_user',
            field=models.ManyToManyField(to='welkin.User'),
        ),
    ]
