# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-14 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        ('crm', '0004_maintions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(to='rbac.Role', verbose_name='用户拥有的角色'),
        ),
    ]
